site_name: "MkDocs Coverage Plugin"
site_description: "MkDocs plugin to integrate your coverage HTML report into your site."
site_url: "https://pawamoy.github.io/mkdocs-coverage"
repo_url: "https://github.com/pawamoy/mkdocs-coverage"
repo_name: "pawamoy/mkdocs-coverage"
site_dir: "site"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Code Reference:
  - loggers.py: reference/loggers.md
  - plugin.py: reference/plugin.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage
- mkdocstrings:
    watch:
    - src/mkdocs_coverage
- macros:
    module_name: docs/macros
